dist: focal
sudo: false
rvm:
  - 2.7

env:
  global:
    - TF_VERSION="0.12.29"
    - BOSH_CLI_VERSION="2.0.48"
    - PROMETHEUS_VERSION="2.6.1"
    - DEPLOY_ENV="travis"
    - SHELLCHECK_VERSION="0.7.1"
    - TMPDIR="/tmp"

addons:
  apt:
    sources:
      - git-core
    packages:
      - git
      - gnupg

before_install:
  - |
    mkdir ~/bin
    export PATH=~/bin:$PATH
  - |
    echo "Fetching shellcheck"
    wget -qO- "https://github.com/koalaman/shellcheck/releases/download/v${SHELLCHECK_VERSION}/shellcheck-v${SHELLCHECK_VERSION}.linux.x86_64.tar.xz" | tar -xJv
    cp "shellcheck-v${SHELLCHECK_VERSION}/shellcheck" ~/bin
  - |
    echo "Fetching Terraform"
    set -e
    wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
    unzip -o terraform_${TF_VERSION}_linux_amd64.zip -d ~/bin
    rm terraform_${TF_VERSION}_linux_amd64.zip
    set +e
  - |
    echo "Fetching bosh cli v2"
    set -e
    wget https://s3.amazonaws.com/bosh-cli-artifacts/bosh-cli-${BOSH_CLI_VERSION}-linux-amd64
    mv bosh-cli-${BOSH_CLI_VERSION}-linux-amd64 ~/bin/bosh && chmod +x ~/bin/bosh
    set +e
  - |
    echo "Fetching Promtool ${PROMETHEUS_VERSION}"
    set -e
    wget -O prometheus.tgz "https://github.com/prometheus/prometheus/releases/download/v${PROMETHEUS_VERSION}/prometheus-${PROMETHEUS_VERSION}.linux-amd64.tar.gz"
    tar xzf "prometheus.tgz" \
       -C $HOME/bin/ \
       --wildcards \
       --wildcards-match-slash \
       --strip-components=1 \
       '*promtool'
    set +e
  - pip install --user yamllint
  - GIMME_OUTPUT=$(gimme 1.13 | tee -a $HOME/.bashrc) && eval "$GIMME_OUTPUT"
  - export GOPATH=$HOME/gopath
  - export PATH=$HOME/gopath/bin:$PATH
  - mkdir -p $HOME/gopath/src/github.com/alphagov/paas-cf
  - rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/alphagov/paas-cf/
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/alphagov/paas-cf
  - cd $HOME/gopath/src/github.com/alphagov/paas-cf
  - (cd tools/pipecleaner && go install -mod=vendor)
  - bundle install

jobs:
  - stage: ci
    name: 'Config spec'
    script: make config_spec

  - stage: ci
    name: 'Scripts spec'
    script: make scripts_spec

  - stage: ci
    name: 'Tools spec'
    script: make tools_spec

  - stage: ci
    name: 'Concourse spec'
    script: make concourse_spec

  - stage: ci
    name: 'Manifests spec'
    script: make manifests_spec

  - stage: ci
    name: 'Terraform spec'
    script: make terraform_spec

  - stage: ci
    name: 'Platform tests spec'
    script: make platform_tests_spec

  - stage: ci
    name: 'Platform tests compilation'
    script: make compile_platform_tests

  - stage: ci
    name: 'Lint'
    script: make lint
