---
- type: replace
  path: /releases/-
  value:
    name: "bosh-dns"
    version: "1.23.0"
    url: "https://bosh.io/d/github.com/cloudfoundry/bosh-dns-release?v=1.23.0"
    sha1: "0fc80540e94c15000c394ef28548fe1cfad5365b"

- type: replace
  path: /addons/-
  value:
    name: bosh-dns
    jobs:
    - name: bosh-dns
      release: bosh-dns
      properties:
        metrics:
          address: 0.0.0.0
          enabled: true
        log_level: WARN
        api:
          client:
            tls:
              ca: ((dns_api_client_tls.ca))
              certificate: ((dns_api_client_tls.certificate))
              private_key: ((dns_api_client_tls.private_key))
          server:
            tls:
              ca: ((dns_api_server_tls.ca))
              certificate: ((dns_api_server_tls.certificate))
              private_key: ((dns_api_server_tls.private_key))
        cache:
          enabled: true
        health:
          client:
            tls:
              ca: ((dns_healthcheck_client_tls.ca))
              certificate: ((dns_healthcheck_client_tls.certificate))
              private_key: ((dns_healthcheck_client_tls.private_key))
          enabled: true
          server:
            tls:
              ca: ((dns_healthcheck_server_tls.ca))
              certificate: ((dns_healthcheck_server_tls.certificate))
              private_key: ((dns_healthcheck_server_tls.private_key))

- type: replace
  path: /variables/-
  value:
    name: dns_healthcheck_tls_ca
    type: certificate
    options:
      is_ca: true
      common_name: dns-healthcheck-tls-ca

- type: replace
  path: /variables/-
  value:
    name: dns_healthcheck_server_tls
    type: certificate
    options:
      ca: dns_healthcheck_tls_ca
      common_name: health.bosh-dns
      extended_key_usage:
      - server_auth

- type: replace
  path: /variables/-
  value:
    name: dns_healthcheck_client_tls
    type: certificate
    options:
      ca: dns_healthcheck_tls_ca
      common_name: health.bosh-dns
      extended_key_usage:
      - client_auth

- type: replace
  path: /variables/-
  value:
    name: dns_api_tls_ca
    type: certificate
    options:
      is_ca: true
      common_name: dns-api-tls-ca

- type: replace
  path: /variables/-
  value:
    name: dns_api_server_tls
    type: certificate
    options:
      ca: dns_api_tls_ca
      common_name: api.bosh-dns
      extended_key_usage:
      - server_auth

- type: replace
  path: /variables/-
  value:
    name: dns_api_client_tls
    type: certificate
    options:
      ca: dns_api_tls_ca
      common_name: api.bosh-dns
      extended_key_usage:
      - client_auth

