---

- type: replace
  path: /releases/-
  value:
    name: vault
    version: 1.1.6
    url: https://github.com/cloudfoundry-community/vault-boshrelease/releases/download/v1.1.6/vault-1.1.6.tgz
    sha1: f2a1fbf8797a63f4a99386c552a2459108d7541a

- type: replace
  path: /variables/-
  value:
    name: vault_ca
    type: certificate
    options:
      is_ca: true
      common_name: vaultCA

- type: replace
  path: /variables/-
  value:
    name: vault_tls
    type: certificate
    options:
      ca: vault_ca
      common_name: vault
      extended_key_usage:
        - client_auth
        - server_auth
      alternative_names:
        - 127.0.0.1
        - localhost
        - "*.vault.service.cf.internal"
        - vault.service.cf.internal

- type: replace
  path: /instance_groups/-
  value:
    name: vault
    instances: 1
    azs: [z1, z2, z3]
    networks: [{name: cf}]

    persistent_disk_type: 10GB

    stemcell: default
    vm_type: small
    vm_extensions:
      - vault_instance_profile

    jobs:
      - name: vault
        release: vault
        properties:
          vault:
            config: |
              storage "file" {
                  path = "/var/vcap/store/vault/data"
              }

              ui = true

              listener "tcp" {
                address = "0.0.0.0:8200"
                tls_cert_file = "/var/vcap/jobs/vault/tls/vault/cert.pem"
                tls_key_file  = "/var/vcap/jobs/vault/tls/vault/key.pem"
                tls_min_version = "tls12"
              }

            additional_config:
              - name: kms.json
                config: |
                  {
                    "seal": [
                      {
                        "awskms": [
                          {
                            "kms_key_id": "b1380431-d93c-4428-85b7-3589deb42e70"
                          }
                        ]
                      }
                    ]
                  }
            tls:
              - name: vault
                key: ((vault_tls.private_key))
                cert: |
                  ((vault_tls.certificate))
                  ((vault_tls.ca))

      - name: route_registrar
        release: routing
        properties:
          route_registrar:
            routes:
              - name: vault
                tls_port: 8200
                prepend_instance_index: false
                registration_interval: 10s
                uris:
                  - vault.((system_domain))
                server_cert_domain_san: vault.service.cf.internal
