---
- type: remove
  path: /instance_groups/name=router/vm_extensions

- type: remove
  path: /instance_groups/name=router/jobs/name=gorouter/properties/routing_api

- type: replace
  path: /instance_groups/name=router/jobs/name=gorouter/properties/router/drain_wait?
  value: 120

- type: replace
  path: /instance_groups/name=router/jobs/name=gorouter/properties/router/tls_port?
  value: 8443

- type: replace
  path: /instance_groups/name=router/jobs/name=gorouter/properties/router/status/user
  value: router_user

- type: replace
  path: /instance_groups/name=router/jobs/name=gorouter/properties/router/http_rewrite?
  value:
    responses:
      add_headers_if_not_present:
        - name: Strict-Transport-Security
          value: max-age=31536000; includeSubDomains; preload

- type: replace
  path: /instance_groups/name=router/jobs/name=gorouter/properties/router/max_idle_connections?
  # See: https://docs.cloudfoundry.org/adminguide/routing-keepalive.html
  #
  # When this is non-zero, gorouter maintains 100 idle connections with
  # backends (hardcoded)
  #
  # When this is non-zero, gorouter maintains the configured value idle
  # connections
  #
  # Enabling this will introduce some base unreliability due to keepalives
  value: 0

- type: replace
  path: /instance_groups/name=router/networks/0/name
  value: router

- type: replace
  path: /instance_groups/name=router/vm_extensions?/-
  value: cf_router_target_groups

- type: replace
  path: /instance_groups/name=router/jobs/name=gorouter/properties/router/ca_certs
  value: |
    ((diego_instance_identity_ca.ca))
    ((cc_tls.ca))
    ((uaa_ssl.ca))
    ((network_policy_server_external.ca))
    ((credhub_tls.ca))
    ((vault_tls.ca))
